jwt:
  secret: asdqwfjidjogwieogkdnvoiweogiweywhrudjbf
  access-expire: 1000000000
  refresh-expire: 1000000000

app:
  client-base-url: http://localhost:3000
  server-base-url: http://localhost:8080
  ai-base-url: http://localhost:5000

minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    images: images       # Public 버킷
    resume: resume       # Private 버킷

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ablej
    username: ablej
    password: ablej

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ablej
      repositories:
        enabled: false


