INSERT INTO public.job VALUES (1, '백엔드 개발자');
INSERT INTO public.job VALUES (2, 'AI 엔지니어');
INSERT INTO public.job VALUES (3, '프론트엔드 개발자');
INSERT INTO public.job VALUES (4, 'AI 연구원');
INSERT INTO public.job VALUES (5, '데이터 분석가');
INSERT INTO public.job VALUES (6, '딥러닝 개발자');
INSERT INTO public.job VALUES (7, '데이터 사이언티스트');
INSERT INTO public.job VALUES (8, '데이터 엔지니어');
INSERT INTO public.job VALUES (9, '시스템 엔지니어');
INSERT INTO public.job VALUES (10, '프로덕트 오너');
INSERT INTO public.job VALUES (11, '소프트웨어 엔지니어');
INSERT INTO public.job VALUES (12, '풀스택 개발자');
INSERT INTO public.job VALUES (13, '보안 엔지니어');
INSERT INTO public.job VALUES (14, '머신러닝 엔지니어');
INSERT INTO public.job VALUES (15, '데이터 거버넌스');
INSERT INTO public.job VALUES (16, '컴퓨터 비전 엔지니어');
INSERT INTO public.job VALUES (17, '테스트 엔지니어');
INSERT INTO public.job VALUES (18, '데이터 품질 관리자');
INSERT INTO public.job VALUES (19, '데브옵스 엔지니어');
INSERT INTO public.job VALUES (20, '운영 매니저');
INSERT INTO public.job VALUES (21, '자연어 처리 엔지니어');
INSERT INTO public.job VALUES (22, '데이터 매니저');
INSERT INTO public.job VALUES (23, '프로젝트 매니저');
INSERT INTO public.job VALUES (24, '데이터베이스 관리자');
INSERT INTO public.job VALUES (25, '검색 엔지니어');
INSERT INTO public.job VALUES (26, 'BI 개발자');
INSERT INTO public.job VALUES (27, 'MLOps 엔지니어');
INSERT INTO public.job VALUES (28, '클라우드 엔지니어');
INSERT INTO public.job VALUES (29, '데이터 분석 엔지니어');
INSERT INTO public.job VALUES (30, '딥러닝 엔지니어');
INSERT INTO public.job VALUES (31, '네트워크 엔지니어');
INSERT INTO public.job VALUES (32, '서버 개발자');
INSERT INTO public.job VALUES (33, 'BI 엔지니어');
INSERT INTO public.job VALUES (34, '모델러');
INSERT INTO public.job VALUES (35, '연구 엔지니어');
INSERT INTO public.job VALUES (36, '데이터 검증 엔지니어');
INSERT INTO public.job VALUES (37, '데이터베이스 엔지니어');
INSERT INTO public.job VALUES (38, '자연어 처리 연구원');
INSERT INTO public.job VALUES (39, '디지털 컨설턴트');
INSERT INTO public.job VALUES (40, '머신러닝 연구원');
INSERT INTO public.job VALUES (41, '데이터 아키텍트');
INSERT INTO public.job VALUES (42, '인프라 엔지니어');